### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by kman3107** [noiamhippyman/MinecraftForgeModdingTools#1]
How about adding forge and mapping versions as options as well?
Just have them at default value, and those that want to can change them before building.

**Comment by noiamhippyman** [comment]
I'm definitely open to doing this if you have any suggestions on downloading mdk versions with gdscript. I wasn't sure how to directly download the mdk since they put the downloads behind an ad-wall and I'm not planning on hosting any files.

**Comment by kman3107** [comment]
<s>What I was thinking was more of how you're changing the mod.toml file.
1. Just use the mdk you bundled with it first to get the gradle files.
2. Then once you have build.gradle you can edit the pertinent parts.

Honestly. I don't know if this is easy or hard. I just assumed that since you can edit the mod.toml file
you should be able to edit the build.gradle file.</s>

EDIT: I see you already are editing the guild.gradle. As for how to make this an option in the setup.
I am sorry but I have no idea. If I did I would've made this myself, not even kidding.

All you really need is to edit the build.gradle fil. The setup will do the new forge and mapping downloads by itself just like it does when you build it normally.

EDIT2: When I make new projects I use the 31.1.0 mdk but I change my build.gradle and gradle.properties with ones I copied from [Cadiboo's Example-Mod](https://github.com/Cadiboo/Example-Mod), before I build it.

**Comment by noiamhippyman** [comment]
Oh so I can update the forge api the same way that I update the MCP mappings? I thought I had to completely redownload the MDK depending on which forge version is needed.

I should mention I'm pretty much completely new to java so I don't really know how gradle works.

**Comment by noiamhippyman** [comment]
I suppose the simplest thing I could do is just let you type in the version directly. Of course then it would be the users' responsibility to input the correct version number. Initially I just figured making it the most recent version of forge was ideal.

**Comment by kman3107** [comment]
can't you do something like

if(user_input == null) {
    do nothing;
} else {
    use the input;
}

No?

**Comment by noiamhippyman** [comment]
Honestly the more I mess around with this and try to find a good solution, the less important this seems. I may come back to this if more people ever become interested. But for now I'm going to keep it with the most recent stable mdk and daily mcp snapshot. If you really want to change these things you can still do it easily manually.
